# Generated by Django 3.1 on 2020-08-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb', models.CharField(blank=True, max_length=250)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('house_type', models.CharField(max_length=150)),
                ('method', models.CharField(max_length=150)),
                ('date', models.DateField(blank=True)),
                ('price', models.FloatField(blank=True)),
                ('rooms', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
