# Generated by Django 3.1 on 2020-08-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseprice_ajax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('h', 'House'), ('t', 'Townhouse'), ('u', 'Unit'), ('br', 'Bedroom')], max_length=150),
        ),
        migrations.AlterField(
            model_name='house',
            name='method',
            field=models.CharField(choices=[('s', 'sold'), ('sp', 'property sold prior'), ('pi', 'property passed in'), ('pn', ' sold prior not disclosed'), ('nb', 'no bid'), ('sa', 'sold after auction'), ('N/A', 'price or highest bid not available')], max_length=150),
        ),
    ]
