# Generated by Django 3.1 on 2020-09-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseprice_ajax', '0003_auto_20200831_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.CharField(choices=[('br', 'bedroom(s)'), ('h', 'house,cottage,villa, semi,terrace'), ('u', 'unit, duplex'), ('t', 'townhouse')], max_length=150),
        ),
        migrations.AlterField(
            model_name='house',
            name='method',
            field=models.CharField(choices=[('S', 'property sold'), ('SP', ' property sold prior'), ('PI ', ' property passed in'), ('PN ', 'sold prior not disclosed'), ('NB ', 'no bid')], max_length=150),
        ),
    ]
